FROM node:22-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache libc6-compat

COPY package*.json ./
RUN npm install

# Source code mounted via volume
EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1

CMD ["npm", "run", "dev"]
