-- Extend audit actions with social-promotion admin moderation events
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_RETRIED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_DISQUALIFIED';

-- Extend activity types with MP Connect and social-promotion lifecycle events
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'MP_CONNECT_CONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'MP_CONNECT_DISCONNECTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_DRAFT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_POST_SUBMITTED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_POST_DISQUALIFIED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_SETTLED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_GRANT_ISSUED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_BONUS_USED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'SOCIAL_PROMOTION_BONUS_REVERSED';
